const fs = require('fs');
const path = require('path');

const artifactPath = path.join(
  __dirname,
  '..',
  'artifacts',
  'contracts',
  'PassageLedger.sol',
  'PassageLedger.json'
);

if (!fs.existsSync(artifactPath)) {
  console.error('Artifact not found. Run `npm run compile` first.');
  process.exit(1);
}

const artifact = JSON.parse(fs.readFileSync(artifactPath, 'utf8'));
const outPath = path.join(__dirname, '..', 'artifacts', 'PassageLedger.abi.js');

const content = `// Auto-generated by scripts/export-abi.js - do not edit by hand.\nexport const abi = ${JSON.stringify(
  artifact.abi,
  null,
  2
)};\n`;

fs.writeFileSync(outPath, content, 'utf8');
console.log('Wrote', outPath);
